DELETE http://localhost:3001/api/blogs/68ceedb465b851b8f6664841
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZCBwZW9wbGUiLCJpZCI6IjY4Y2U5NmI3NGQ1N2VjODE1ZDU0MGE5MCIsImlhdCI6MTc1ODM5MjA2OX0.YEA2z_jyJRfLe4k2JMNMDYU8nXloQu6-kTjVSlzhzAE